import Head from 'next/head';
import { Inter } from 'next/font/google';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from 'next/image';
import peter_chen_avatar2 from '../public/peter_chen_avatar2.png';
import css3 from '../public/css3.png';
import git from '../public/git.png';
import github from '../public/github.png';
import html5 from '../public/html5.png';
import javascript from '../public/javascript.png';
import react from '../public/react.png';
import restapi from '../public/restapi.png';
import vscode from '../public/vscode.png';
import website from '../public/website.png';
import tailwind from '../public/tailwind.png';
import mongodb from '../public/mongodb.png';
import next from '../public/next.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState, useRef} from 'react';
import {useFormik} from 'formik';
import * as Yup from 'yup';
import { useRouter } from 'next/router';
import {motion as m} from 'framer-motion';
import emailjs from '@emailjs/browser';
import InsertLinkIcon from '@mui/icons-material/InsertLink';
import GitHubIcon from '@mui/icons-material/GitHub';




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  //Router
  const router = useRouter();
  
  

  // Formik logic

  const formik = useFormik({
    initialValues: {
      name:"",
      email:"",
      message:"",
    }, 

    //validation
    validationSchema: Yup.object({
      name: Yup.string()
      .required('Name is required')
      .max(20, 'Name must be 20 characters or less.'),
      email: Yup.string()
      .email('Invalid email')
      .required('Email is required'),
      message: Yup.string()
      .required('Message is required'),
  }),
    // submit form
  //   onSubmit: (values) => {
  //   console.log(values);
  //   router.push({pathname:'/success', query: values});
  // },

  });

    //emailjs
    const form = useRef();
    const sendEmail = (e) => {
    e.preventDefault();
    
    emailjs.sendForm('service_53wuam9', 'template_l3f38ku', form.current, '38tiSpfDvWmJL9aVR')
      .then((result) => {
          console.log(result.text);
          console.log("message sent");
          // Navigate to the success page after the email is sent
      router.push('/success');
      }, (error) => {
          console.log(error.text);
      });
  };

  return (
    <div className={darkMode && "dark"}>
      <Head>
        <title>Peter Chen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet" />

      </Head>
      <m.main 
      initial={{ opacity:0 }}
      animate={{ opacity:1 }}
      exit={{ opacity:0}}
      className='bg-white px-10 md:px-20 lg:px-40 dark:bg-zinc-800'>

      {/* frontpage */}
        <section className='min-h-screen relative'>
          <nav 
          className='py-5 mb-12 flex justify-between 
          fixed top-0 left-0 right-0 px-10
          md:px-20 lg:px-40
          z-50 bg-white dark:bg-zinc-800'>
            <h1 className='text-2xl font-pacifico text-gray-800 dark:text-gray-600'>TeamPickle</h1>
            <ul className='flex items-center '>
              <li>
              <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)}className='cursor-pointer text-2xl text-gray-800 dark:text-white'/>
              </li>
              <li>
              <a 
              className='bg-gradient-to-r from-cyan-400 to bg-sky-900 px-4 py-2 ml-8 rounded'
              href="https://drive.google.com/uc?export=download&id=1IHB57WbbhjHb9-6te7-a09qRMdmUF021"
              target="_blank" >
              Resume
              </a>
              </li>
            </ul>
          </nav>          
          <div className='outer-headings flex text-center py-10'>
            <h2 className='text-3xl leading-relaxed md:leading-relaxed lg:leading-relaxed py-2 px-10 mt-20 text-cyan-600 font-normal md:text-4xl lg:text-5xl'>
            Hi, I'm Peter! <br />
            I'm a <span className='font-bold'>Mechanical Engineer turned Developer</span><br /> 
            <div className="flex items-center pl-8 md:pl-40 lg:pl-60">
            and
            <div className="inner-headings text-left ml-4 my-auto">
              <span>
                Athlete. ⛹🏻<br />
                Optimist. 🍀<br />
                Human GPS. 📍<br />
                Ramen Enthusiast. 🍜<br />
                French Bulldog Dad. 🐶<br />
              </span>
            </div> 
            </div> 
            
            </h2>
          </div>
          
          <div className='relative mx-auto rounded-full w-80 h-80 my-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={peter_chen_avatar2}/>
          </div>
        </section>
        <section>
          <div className='container mx-auto text-center my-20'>
            <h3 className='text-3xl pt-1 text-gray-800 dark:text-gray-400'>My Toolbox & Things I Can Do</h3>
          <div className="flex flex-wrap justify-center items-center my-20">
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8 ">
             <Image src={html5} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>HTML5</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={css3} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>CSS3</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={javascript} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>JavaScript</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={react} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>React</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={git} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>Git</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={github} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>Github</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={restapi} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>Restful APIs</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={tailwind} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>Tailwind</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={mongodb} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>MongoDB</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={next} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>Next.js</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={vscode} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>VS Code</p>
           </div>
           <div className="w-1/3 md:w-1/4 lg:w-1/6 p-8">
             <Image src={website} className='w-12 mx-auto contrast-50 dark:contrast-0'/>
            <p className='mt-2 text-md text-gray-500 dark:text-gray-400'>Responsive Websites</p>
           </div>
          </div>
          </div> 
        </section>

        {/* portfolio */}
        <section>
        <div className='text-center'>
          <h3 className='text-3xl py-1 text-gray-800 dark:text-gray-400'>Portfolio</h3>
          <p className='text-md py-5 leading-8 text-gray-500 dark:text-gray-400'>
            A Selection Of My Recent Work
            </p>
        </div>
        {/* card */} 
        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
        {/* web1 */} 
          <div className='basis-1/3 flex-1'>
          <div className="relative group transition-transform duration-800 hover:scale-110 rounded-lg overflow-hidden">
            <Image src={web1} className="rounded-lg object-cover shadow-lg " 
            width={'100%'} height={'100%'} layout="responsive"/>
            <div 
            className="absolute top-0 left-0 right-0 bottom-0 z-10
            flex flex-col items-center justify-center
            bg-gray-800 bg-opacity-80 text-white text-center opacity-0 group-hover:opacity-100
            ">
            <div className='flex flex-col items-center justify-center'>
              <h3 className='text-2xl mt-10'>Pokemon Wiki</h3>
              <p className='text-sm mt-4 px-24'>I developed a comprehensive Pokemon encyclopedia utilizing the Pokemon API and React.js framework.</p>
              <p className='text-base mt-4'>Tech Stack:</p>
              <div className="flex mx-4 mt-2">
                <p className='text-sm px-1 bg-gray-900 rounded'>React</p>
                <p className='text-sm px-1 ml-2 bg-gray-900 rounded'>API</p>
              </div>
        {/* on hover */}
            </div>
                <div className='flex justify-center '>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://team-pickle-pokemonwiki.netlify.app/" target="_blank" rel="noopener noreferrer">Visit the site<InsertLinkIcon className='ml-2'/></a>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://github.com/nonsense-bucket/pokemonAPI" target="_blank" rel="noopener noreferrer">See the code<GitHubIcon className='ml-2'/></a>
                </div>
            </div>
          </div>
          </div>
           {/* web2 */} 
          <div className='basis-1/3 flex-1'>
          <div className="relative group transition-transform duration-800 hover:scale-110 rounded-lg overflow-hidden">
            <Image src={web2} className="rounded-lg object-cover shadow-lg " 
            width={'100%'} height={'100%'} layout="responsive"/>
            <div 
            className="absolute top-0 left-0 right-0 bottom-0 z-10
            flex flex-col items-center justify-center
            bg-gray-800 bg-opacity-80 text-white text-center opacity-0 group-hover:opacity-100
            ">
            <div className='flex flex-col items-center justify-center'>
              <h3 className='text-2xl mt-10'>Advanced To-do List</h3>
              <p className='text-sm mt-4 px-24'>This is a robust todo list application with comprehensive features such as adding, deleting, and changing the status of items. It comes with a filtering mechanism to efficiently organize tasks based on their status.</p>
              <p className='text-base mt-4'>Tech Stack:</p>
              <div className="flex mx-4 mt-2">
                <p className='text-sm px-1 bg-gray-900 rounded'>React</p>
              </div>
        {/* on hover */}
            </div>
                <div className='flex justify-center '>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://team-pickle-better-to-do.netlify.app/" target="_blank" rel="noopener noreferrer">Visit the site<InsertLinkIcon className='ml-2'/></a>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://github.com/nonsense-bucket/better_to_do" target="_blank" rel="noopener noreferrer">See the code<GitHubIcon className='ml-2'/></a>
                </div>
            </div>
          </div>
          </div>

          {/* web3 */} 
          <div className='basis-1/3 flex-1'>
          <div className="relative group transition-transform duration-800 hover:scale-110 rounded-lg overflow-hidden">
            <Image src={web3} className="rounded-lg object-cover shadow-lg " 
            width={'100%'} height={'100%'} layout="responsive"/>
            <div 
            className="absolute top-0 left-0 right-0 bottom-0 z-10
            flex flex-col items-center justify-center
            bg-gray-800 bg-opacity-80 text-white text-center opacity-0 group-hover:opacity-100
            ">
            <div className='flex flex-col items-center justify-center'>
              <h3 className='text-2xl mt-10'>"Craving" - Recipe for Tonight</h3>
              <p className='text-sm mt-4 px-24'>
I have developed a food recipe application utilizing a recipe API to fetch and display recipe data in an elegant card-based system. This project showcases my expertise as a frontend developer in creating interactive and visually appealing user interfaces for culinary enthusiasts.</p>
              <p className='text-base mt-4'>Tech Stack:</p>
              <div className="flex mx-4 mt-2">
                <p className='text-sm px-1 bg-gray-900 rounded'>React</p>
                <p className='text-sm px-1 ml-2 bg-gray-900 rounded'>API</p>
              </div>
        {/* on hover */}
            </div>
                <div className='flex justify-center '>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://teampickle-react-recipe-app.netlify.app/" target="_blank" rel="noopener noreferrer">Visit the site<InsertLinkIcon className='ml-2'/></a>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://github.com/nonsense-bucket/react-recipe-app" target="_blank" rel="noopener noreferrer">See the code<GitHubIcon className='ml-2'/></a>
                </div>
            </div>
          </div>
          </div>
         {/* web4 */} 
         <div className='basis-1/3 flex-1'>
          <div className="relative group transition-transform duration-800 hover:scale-110 rounded-lg overflow-hidden">
            <Image src={web4} className="rounded-lg object-cover shadow-lg " 
            width={'100%'} height={'100%'} layout="responsive"/>
            <div 
            className="absolute top-0 left-0 right-0 bottom-0 z-10
            flex flex-col items-center justify-center
            bg-gray-800 bg-opacity-80 text-white text-center opacity-0 group-hover:opacity-100
            ">
            <div className='flex flex-col items-center justify-center'>
              <h3 className='text-2xl mt-10'>Calculator with React</h3>
              <p className='text-sm mt-4 px-24'>I have developed a web-based calculator utilizing React during the initial stages of my learning journey. This project represents my commitment to expanding my skills as a front-end developer and demonstrates my ability to apply React concepts in practical applications.</p>
              <p className='text-base mt-4'>Tech Stack:</p>
              <div className="flex mx-4 mt-2">
                <p className='text-sm px-1 bg-gray-900 rounded'>React</p>
                
              </div>
        {/* on hover */}
            </div>
                <div className='flex justify-center '>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://team-pickle-calculator.netlify.app/" target="_blank" rel="noopener noreferrer">Visit the site<InsertLinkIcon className='ml-2'/></a>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://github.com/nonsense-bucket/calculator-app" target="_blank" rel="noopener noreferrer">See the code<GitHubIcon className='ml-2'/></a>
                </div>
            </div>
          </div>
          </div>

        {/* web5 */} 
        <div className='basis-1/3 flex-1'>
          <div className="relative group transition-transform duration-800 hover:scale-110 rounded-lg overflow-hidden">
            <Image src={web5} className="rounded-lg object-cover shadow-lg " 
            width={'100%'} height={'100%'} layout="responsive"/>
            <div 
            className="absolute top-0 left-0 right-0 bottom-0 z-10
            flex flex-col items-center justify-center
            bg-gray-800 bg-opacity-80 text-white text-center opacity-0 group-hover:opacity-100
            ">
            <div className='flex flex-col items-center justify-center'>
              <h3 className='text-2xl mt-10'>A Cocktail Database</h3>
              <p className='text-sm mt-4 px-24'> This is another project that I worked with APIs. It is an advanced cocktail database with integrated routing capabilities for seamless navigation between pages. Each cocktail variety is elegantly showcased on a comprehensive individual card.</p>
              <p className='text-base mt-4'>Tech Stack:</p>
              <div className="flex mx-4 mt-2">
                <p className='text-sm px-1 bg-gray-900 rounded'>React</p>
                <p className='text-sm px-1 ml-2 bg-gray-900 rounded'>API</p>
                
              </div>
        {/* on hover */}
            </div>
                <div className='flex justify-center '>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://team-pickle-cocktail-pedia.netlify.app/" target="_blank" rel="noopener noreferrer">Visit the site<InsertLinkIcon className='ml-2'/></a>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://github.com/nonsense-bucket/cocktail-pedia" target="_blank" rel="noopener noreferrer">See the code<GitHubIcon className='ml-2'/></a>
                </div>
            </div>
          </div>
          </div>
          
          {/* web6 */} 
        <div className='basis-1/3 flex-1'>
          <div className="relative group transition-transform duration-800 hover:scale-110 rounded-lg overflow-hidden">
            <Image src={web6} className="rounded-lg object-cover shadow-lg " 
            width={'100%'} height={'100%'} layout="responsive"/>
            <div 
            className="absolute top-0 left-0 right-0 bottom-0 z-10
            flex flex-col items-center justify-center
            bg-gray-800 bg-opacity-80 text-white text-center opacity-0 group-hover:opacity-100
            ">
            <div className='flex flex-col items-center justify-center'>
              <h3 className='text-2xl mt-10'>The Simon Game</h3>
              <p className='text-sm mt-4 px-24'> A reacreation of the classic Simon Game using vanilla javascript, jQuery and DOM manipulation. </p>
              <p className='text-base mt-4'>Tech Stack:</p>
              <div className="flex mx-4 mt-2">
                <p className='text-sm px-1 bg-gray-900 rounded'>Javascript</p>
                <p className='text-sm px-1 ml-2 bg-gray-900 rounded'>jQuery</p>
                
              </div>
        {/* on hover */}
            </div>
                <div className='flex justify-center '>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://team-pickle-simon-game.netlify.app/" target="_blank" rel="noopener noreferrer">Visit the site<InsertLinkIcon className='ml-2'/></a>
                <a className='flex px-3 py-1 my-8 mx-4 bg-cyan-600 rounded' href="https://github.com/nonsense-bucket/simon-game" target="_blank" rel="noopener noreferrer">See the code<GitHubIcon className='ml-2'/></a>
                </div>
            </div>
          </div>
          </div>
          
          
          
        </div>
        </section>
        
        {/* contact form */}
        <section className='my-20 flex items-center justify-center'>
        <form 
        ref={form}
        onSubmit={sendEmail} 
        className='bg-white dark:bg-zinc-600 flex rounded-lg  '>
          <div className='p-10 flex-1 text-gray-800 dark:text-gray-400'>
            <h1 className='text-3xl pb-2'>Let's get in touch! 👋🏻 </h1>
            <p className='text-lg '>
            Join my adventure from a Mechanical Engineer to Web Developer! 
            Find out what I have to offer to boost your business. </p>
            <div className='mt-6'>
            <div className="pb-4">
            <div className="flex flex-wrap">
            {/* name input field */}
          <div className="w-full sm:w-1/2 pr-2">
            <label className={`block text-sm pb-2 ${formik.touched.name && formik.errors.name ? "text-red-400" : ""}`} htmlFor="name">
            {formik.touched.name && formik.errors.name ? formik.errors.name : "name"}
            </label>
            <input 
            className='border-2 dark:border-zinc-700 p-2 rounded-md w-full focus: outline-none focus:border-cyan-600 focus:ring-cyan-400 dark:bg-zinc-500' 
            type="text" 
            name="name" 
            value={formik.values.name}
            onChange={formik.handleChange}
            onBlur={formik.handleBlur}
            placeholder='Enter your name'/>
          </div>
          {/* email input field */}
          <div className="w-full sm:w-1/2 pr-2 sm:pl-2">
            <label className={`block text-sm pb-2 ${formik.touched.email && formik.errors.email ? "text-red-400" : ""}`} htmlFor="email">
            {formik.touched.email && formik.errors.email ? formik.errors.email : "email"}
            </label>
            <input 
            className='border-2 dark:border-zinc-700 p-2 rounded-md w-full focus: outline-none focus:border-cyan-600 focus:ring-cyan-400 dark:bg-zinc-500' 
            type="text" 
            name="email" 
            value={formik.values.email}
            onChange={formik.handleChange}
            onBlur={formik.handleBlur}
            placeholder='Enter your email'/>
          </div>  
          </div>
          {/* message input field */}
          <div className='pt-5'>
            <label className={`block text-sm pb-2 ${formik.touched.message && formik.errors.message ? "text-red-400" : ""}`}htmlFor="message">
            {formik.touched.message && formik.errors.message ? formik.errors.message : "message"}
            </label>
            <textarea rows="3" 
            className='border-2 dark:border-zinc-700 p-2 rounded-md w-full focus: outline-none focus:border-cyan-600 focus:ring-cyan-400 dark:bg-zinc-500' 
            type="text" 
            name="message" 
            value={formik.values.message}
            onChange={formik.handleChange}
            onBlur={formik.handleBlur}
            placeholder='Enter your message'/>
          </div>  
            </div>
            </div>
            <button type="submit" className='bg-cyan-600 text-sm text-white dark:text-gray-800 py-3 mt-6 rounded-lg w-full'>Submit</button>
          </div>
        </form>
        </section>

        {/* social */}
        <div className='my-20 text-4xl flex justify-center gap-16 text-gray-800 dark:text-gray-400'>
            <p className='text-3xl pb-2'>Feeling social? </p>
            <a href="https://www.linkedin.com/in/zhiyuan-peter-chen-3b20a892/" target="_blank" rel="noopener noreferrer"><AiFillLinkedin /></a>
            <a href="https://github.com/nonsense-bucket" target="_blank" rel="noopener noreferrer"><AiFillGithub /></a>
          </div>

        {/* footer */}
        <footer>
        <div className="container mx-auto px-6 py-4">
        <div className="flex justify-center">
         <div className="text-gray-600 dark:text-gray-400">
        &copy; 2023 TeamPickle. All rights reserved ✨.
        </div>
        </div>
        </div>
        </footer>
      </m.main>
    </div>
  )
}
